//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Vibrancy.Forms")]
[assembly: System.Reflection.AssemblyCompany("Andreas Wäscher")]
[assembly: System.Reflection.AssemblyDescription("Blur and Vibrancy effects for iOS and iPadOS with Xamarin.Forms")]
[assembly: System.Reflection.AssemblyProduct("Vibrancy.Forms")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Andreas Wäscher 2020")]
[assembly: System.Reflection.AssemblyVersion("0.1")]
[assembly: System.Reflection.AssemblyFileVersion("0.1")]


